# Generated by Django 3.2.5 on 2021-07-25 09:24

import Classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to=Classes.models.file_upload_path),
        ),
    ]
