# Generated by Django 3.2.5 on 2021-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0005_post_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
