# Generated by Django 3.2.5 on 2021-07-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_auto_20210730_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
