# Generated by Django 4.1.7 on 2023-06-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='limit',
            field=models.IntegerField(default=60),
        ),
    ]
