# Generated by Django 3.2.5 on 2021-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0007_auto_20210730_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
