# Generated by Django 3.2.6 on 2021-08-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0008_classroom_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Classes.classroom'),
        ),
    ]
