# Generated by Django 4.1.7 on 2023-07-15 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0009_assignment_file_alter_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
