# Generated by Django 4.1.7 on 2023-07-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0010_alter_assignmentsubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
