# Generated by Django 3.2.6 on 2021-09-08 12:50

import Classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0010_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_file',
            field=models.FileField(blank=True, upload_to=Classes.models.file_upload_path),
        ),
    ]
