# Generated by Django 3.2.6 on 2021-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0012_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_file',
            field=models.FileField(blank=True, upload_to='test/'),
        ),
    ]
