# Generated by Django 3.2.5 on 2021-09-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0013_alter_test_test_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
