# Generated by Django 3.2.5 on 2021-07-29 16:19

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_contact_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.file_upload_path),
        ),
    ]
