# Generated by Django 3.2.6 on 2021-09-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customuser_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
